# -*- coding: utf-8 -*-
"""mini_proj_mentalBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOdfBwpRf9nCI5vs9R02xAMpDnFTCNfY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import *
from sklearn.metrics import *
from transformers import BertTokenizer, BertForSequenceClassification,Trainer, TrainingArguments
from datasets import Dataset

df = pd.read_csv("/content/drive/MyDrive/mini project/testing.csv")
df.dropna(inplace = True)
print(df)

df.drop(columns=['Unnamed: 0', 'lemmatized_text'], axis=1, inplace=True)
df.head()

df['status'].value_counts()

import re
import nltk

def clean_statement(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)       # remove URLs
    text = re.sub(r'@\w+', '', text)          # remove @mentions
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # remove special symbols
    text = re.sub(r'\s+', ' ', text).strip()  # normalize whitespace
    return text

df['statement'] = df['statement'].apply(clean_statement)
df.head()

label_encoder = LabelEncoder()
df['label'] = label_encoder.fit_transform(df['status'])
df.head()

print(label_encoder.classes_)

import pickle
pickle.dump(label_encoder, open('/content/drive/MyDrive/mini project/label_encodings1.pkl', 'wb'))

train_texts, test_texts, train_labels, test_labels =
train_test_split(df['statement'], df['label'], test_size=0.2, random_state=42,stratify=df['label'])

print(set(train_labels))

print(max([len(text) for text in df['statement']]))
print(min([len(text) for text in df['statement']]))

import huggingface_hub
huggingface_hub.login()
tokenizer = BertTokenizer.from_pretrained('mental/mental-bert-base-uncased')

token_lengths = [len(tokenizer.encode(text, truncation=False)) for text in df['statement']]

print(f"Max tokens:    {max(token_lengths)}")
print(f"Mean tokens:   {np.mean(token_lengths):.1f}")
print(f"Median tokens: {np.median(token_lengths):.1f}")
print(f"90th percentile: {np.percentile(token_lengths, 90):.1f}")
print(f"95th percentile: {np.percentile(token_lengths, 95):.1f}")
print(f"Samples > 200 tokens:  {sum(l > 200 for l in token_lengths)} ({sum(l > 200 for l in token_lengths)/len(token_lengths)*100:.1f}%)")
print(f"Samples > 512 tokens:  {sum(l > 512 for l in token_lengths)} ({sum(l > 512 for l in token_lengths)/len(token_lengths)*100:.1f}%)")

train_encodings = tokenizer(train_texts.tolist(), padding = True, truncation = True, max_length = 256)
test_encodings = tokenizer(test_texts.tolist(), padding = True, truncation = True, max_length = 256)

train_dataset = Dataset.from_dict({'input_ids':train_encodings['input_ids'], 'attention_mask':train_encodings['attention_mask'], 'labels':train_labels.tolist()})
test_dataset = Dataset.from_dict({'input_ids':test_encodings['input_ids'], 'attention_mask':test_encodings['attention_mask'], 'labels':test_labels.tolist()})

model = BertForSequenceClassification.from_pretrained('mental/mental-bert-base-uncased', num_labels=len(label_encoder.classes_))

training_args = TrainingArguments(
    output_dir = './results',
    eval_strategy = 'epoch',
    save_strategy = 'epoch',
    learning_rate = 2e-5,
    per_device_train_batch_size = 16,
    per_device_eval_batch_size = 32,
    num_train_epochs = 5,
    weight_decay = 0.01,
    warmup_ratio= 0.1,
    load_best_model_at_end = True,
    metric_for_best_model = 'eval_loss',
    greater_is_better = False,
    save_total_limit = 3,
    gradient_accumulation_steps = 2,
    fp16 = True
)
from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import torch

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(train_labels),
    y=train_labels
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
      labels = inputs.get("labels")

      outputs = model(**inputs)
      logits = outputs.get("logits")

      loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights.to(logits.device))
      loss = loss_fn(logits, labels)

      return (loss, outputs) if return_outputs else loss

trainer = WeightedTrainer(
    model = model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)
trainer.train()

id2label = {
    0: "anxiety",
    1: "depression",
    2: "mental_disorder",
    3: "normal",
    4: "suicidewatch"
}

label2id = {v: k for k, v in id2label.items()}

model.config.id2label = id2label
model.config.label2id = label2id

from transformers import  AutoModelForSequenceClassification, AutoTokenizer

trainer.save_model("/content/drive/MyDrive/mini project/mentalbert_results")
tokenizer.save_pretrained("/content/drive/MyDrive/mini project/mentalbert_results")

model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/mini project/mentalbert_results")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/mini project/mentalbert_results")

# trainer = WeightedTrainer(
#     model = model,
#     args=training_args,
#     train_dataset=train_dataset,
#     eval_dataset=test_dataset
# )
predictions, true_labels, _ = trainer.predict(test_dataset)

# Save predictions to Drive after running trainer.predict()
# np.save('/content/drive/MyDrive/mini project/mentalbert_results/predictions.npy', predictions)
# np.save('/content/drive/MyDrive/mini project/mentalbert_results/true_labels.npy', true_labels)

# Load them back next session instantly
# predictions = np.load('/content/drive/MyDrive/mini project/mentalbert_results/predictions.npy')
# labels = np.load('/content/drive/MyDrive/mini project/mentalbert_results/true_labels.npy')

import pickle
label_encodings= pickle.load(open('/content/drive/MyDrive/mini project/label_encodings1.pkl', 'rb'))
predicted_labels = np.argmax(predictions, axis=1)

print (classification_report(test_labels, predicted_labels, target_names = label_encodings.classes_))

cm = confusion_matrix(test_labels, predicted_labels)
plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels= label_encodings.classes_, yticklabels=label_encoder.classes_)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

predicted_labels = np.argmax(predictions, axis=1)
print("Unique predictions:", set(predicted_labels))
print(pd.Series(predicted_labels).value_counts())

import torch

def detection(text):
    text = clean_statement(text)

    model.eval()  # important

    device = next(model.parameters()).device

    inputs = tokenizer(
        text,
        return_tensors='pt',
        padding=True,
        truncation=True,
        max_length=256   # match training
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():  # important
        outputs = model(**inputs)

    logits = outputs.logits
    probs = torch.softmax(logits, dim=1)

    predicted_label = torch.argmax(probs, dim=1).item()
    confidence = probs.max().item()

    label = label_encodings.inverse_transform([predicted_label])[0]

    return {
        "label": label,
        "confidence": round(confidence, 3)
    }

import torch

def detection_top2(text):
    text = clean_statement(text)

    model.eval()

    device = next(model.parameters()).device

    inputs = tokenizer(
        text,
        return_tensors='pt',
        padding=True,
        truncation=True,
        max_length=256
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    probs = torch.softmax(logits, dim=1)

    # Top 2 predictions
    top2 = torch.topk(probs, 2)

    top_labels = []
    top_confidences = []

    for i in range(2):
        label_index = top2.indices[0][i].item()
        confidence = top2.values[0][i].item()

        label = label_encodings.inverse_transform([label_index])[0]

        top_labels.append(label)
        top_confidences.append(round(confidence, 3))

    return {
        "top_1": {"label": top_labels[0], "confidence": top_confidences[0]},
        "top_2": {"label": top_labels[1], "confidence": top_confidences[1]}
    }

sample_texts = [
"I feel perfectly fine today, nothing to worry about.",
"I can't stop thinking about what will happen if things go wrong.",
"Lately, I've been on a high, feeling like I can do anything!",
"I'm so sad, I just can't seem to get out of bed anymore.",
"I'm constantly thinking about how much better everyone else is doing than me.",
"I don't think I can keep going, everything feels so hopeless.",
"I had a really good day, spent some time with my friends.",
"I'm overwhelmed by the idea that I might lose everything.",
"I feel like nothing matters anymore, I just want to give up.",
"I'm okay today, but sometimes I get really anxious for no reason."]

for text in sample_texts:
  predicted_class1 = detection(text)
  predicted_class2 = detection_top2(text)
  print(f"Text: {text}\nPredicted Class: {predicted_class1}\n")
  print(f"Text: {text}\nPredicted Class: {predicted_class2}\n")
  print("_________________________________")

sample_texts = [
    "I have been overthinking every single decision I make lately and my heart just races for no reason at all, I cant sleep because my brain wont stop",
    "I have no energy to do anything anymore, I just lay in bed all day and nothing brings me joy, I dont see the point of trying",
    "I am so tired of waking up every day feeling like this, I dont want to be here anymore and I keep thinking about ending it all",
    "had a pretty chill weekend, went grocery shopping and watched some movies, feeling okay about the week ahead",
    "I keep hearing voices telling me to do things and sometimes I genuinely cannot tell what is real and what isnt, its been going on for weeks",
    "I snapped at my coworker today over nothing and now I cant stop replaying it, why do I always do this",
    "been feeling really low for months now, lost my job and my girlfriend left, I just dont care about anything anymore",
    "my thoughts are going a mile a minute I feel like I can conquer everything today but yesterday I couldnt get out of bed",
    "I know its irrational but I genuinely cannot stop worrying that something bad is going to happen to my family",
    "honestly feel nothing lately, not sad not happy just completely empty, like I am just going through the motions"
]

for text in sample_texts:
  predicted_class = detection(text)
  print(f"Text: {text}\nPredicted Class: {predicted_class}\n")

text = "There's this constant low hum of dread that follows me through the day — not attached to anything specific, not a fear of losing my job or a worry about my health, just a free-floating heaviness that settles over everything like weather, making even neutral moments feel slightly ominous, and I've gotten so used to it that I barely notice it anymore except in the rare moments when it lifts briefly and I suddenly remember what it felt like to just exist without carrying something"
detection(text)