# -*- coding: utf-8 -*-
"""whatsapp-chat-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5gdlBZ4e-QDqiGpHU8P45ZpymsXBGEr
"""

import pandas as pd
import re

f = open("WhatsApp Chat with AI.txt", "r", encoding = "utf-8")

data = f.read()

print(data)

pattern = r"\d{2}/\d{2}/\d{2},\s\d{1,2}:\d{2}[\s\u202f]*[ap]m\s-\s"

msgs = re.split(pattern, data)[1:]
msgs

dates = re.findall(pattern, data)
dates

df = pd.DataFrame({"user_msgs" : msgs, "date" : dates})
df["date"] = pd.to_datetime(df["date"], format = "%d/%m/%y, %I:%M %p - ")

df

df.shape

#separate users and msgs
users = []
msgss = []
for msgs in df["user_msgs"]:
  i = re.split(r"([^:]+):\s(.*)", msgs)
  if i[1:]:
    users.append(i[1])
    msgss.append(i[2])
  else:
    users.append("group_notification")
    msgss.append(i[0])

df["users"] = users
df["msgs"] = msgss
df.drop(["user_msgs"], axis = 1, inplace = True)
df

df["year"] = df["date"].dt.year
df.head()

df["month"] = df["date"].dt.month_name()
df.head()

df["day"] = df["date"].dt.day
df.head()

df["hour"] = df["date"].dt.hour
df["minute"] = df["date"].dt.minute
df.head()

#total no. of msgs --> df.shape

#total no. of words
words = []
for i in df["msgs"]:
  words.extend(i.split(' '))

len(words)

#total no. of media shared
num_media = df[df["msgs"] == "<Media omitted>"]
len(num_media)

#top users
top_users = df[df["users"] != "group_notification"]["users"].value_counts().head()

import matplotlib.pyplot as plt

name = top_users.index
count = top_users.values
plt.bar(name, count)
plt.xticks(rotation = "vertical")
plt.show()

# %age of msgs per user
round((df[df["users"] != "group_notification"]["users"].value_counts()/df.shape[0])*100 ,2).reset_index().rename(columns = {"count":"percent"})

#emoji analysis

!pip install emoji

import emoji
emojis = []
for i in df["msgs"]:
  emojis.extend([c for c in i if emoji.is_emoji(c)])

emojis

from collections import Counter
pd.DataFrame(Counter(emojis).most_common(len(Counter(emojis)))).rename(columns={0: 'Emoji', 1: 'Count'})

df["month_num"] = df["date"].dt.month
df

timeline = df.groupby(["year", "month_num", "month"]).count()["msgs"].reset_index()
timeline

time = []
for i in range(timeline.shape[0]):
  time.append(timeline["month"][i] + "-" + str(timeline["year"][i]))

timeline["time"] = time
timeline

plt.plot(timeline["time"], timeline["msgs"])
plt.xticks(rotation = "vertical")
plt.show()

df["only_date"] = df["date"].dt.date

daily_timeline = df.groupby(["only_date"]).count()["msgs"].reset_index()
daily_timeline

plt.plot(daily_timeline["only_date"], daily_timeline["msgs"])
plt.xticks(rotation = "vertical")
plt.show()